const exportBtn = document.getElementById('exportBtn');
const statusBox = document.getElementById('status');

const COOKIE_URLS = [
  'https://www.youtube.com',
  'https://youtube.com',
  'https://accounts.youtube.com',
  'https://google.com',
  'https://www.google.com',
  'https://accounts.google.com'
];

function setStatus(message, type = '') {
  statusBox.textContent = message;
  statusBox.className = `status ${type}`.trim();
}

function formatExpiry(cookie) {
  if (cookie.session || !cookie.expirationDate) {
    return '0';
  }
  return String(Math.floor(cookie.expirationDate));
}

function toNetscapeLine(cookie) {
  const includeSubdomains = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE';
  const secure = cookie.secure ? 'TRUE' : 'FALSE';
  return [
    cookie.domain,
    includeSubdomains,
    cookie.path || '/',
    secure,
    formatExpiry(cookie),
    cookie.name,
    cookie.value
  ].join('\t');
}

function uniqueCookies(cookies) {
  const map = new Map();
  cookies.forEach((cookie) => {
    const key = `${cookie.domain}|${cookie.path}|${cookie.name}`;
    map.set(key, cookie);
  });
  return [...map.values()].sort((a, b) => {
    const domainCompare = a.domain.localeCompare(b.domain);
    if (domainCompare !== 0) return domainCompare;
    return a.name.localeCompare(b.name);
  });
}

async function getYouTubeCookies() {
  const results = await Promise.all(
    COOKIE_URLS.map((url) => chrome.cookies.getAll({ url }))
  );
  return uniqueCookies(results.flat()).filter((cookie) => {
    const domain = cookie.domain.replace(/^\./, '');
    return domain.endsWith('youtube.com') || domain.endsWith('google.com');
  });
}

function buildCookiesTxt(cookies) {
  const header = [
    '# Netscape HTTP Cookie File',
    '# Generated by YouTube Cookies TXT Exporter',
    '# Compatible with yt-dlp --cookies cookies.txt and pytube cookie_file usage.',
    ''
  ];
  return `${header.join('\n')}${cookies.map(toNetscapeLine).join('\n')}\n`;
}

async function downloadTextFile(filename, text) {
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  try {
    await chrome.downloads.download({
      url,
      filename,
      saveAs: true,
      conflictAction: 'overwrite'
    });
  } finally {
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
}

exportBtn.addEventListener('click', async () => {
  exportBtn.disabled = true;
  setStatus('Mengambil cookies YouTube dari browser...');

  try {
    const cookies = await getYouTubeCookies();
    if (cookies.length === 0) {
      setStatus('Cookies YouTube tidak ditemukan. Login ke YouTube dulu, lalu coba lagi.', 'error');
      return;
    }

    await downloadTextFile('cookies.txt', buildCookiesTxt(cookies));
    setStatus(`Berhasil membuat cookies.txt dengan ${cookies.length} cookies.`, 'success');
  } catch (error) {
    setStatus(`Gagal membuat cookies.txt: ${error.message}`, 'error');
  } finally {
    exportBtn.disabled = false;
  }
});
